const backendFunFacts = [
    "Node.js is built on the V8 JavaScript engine from Google.",
    "The first web server, CERN HTTPd, was created by Tim Berners-Lee in 1990.",
    "SQL stands for Structured Query Language.",
    "Python is a popular language for building backend applications.",
    "Django and Flask are popular Python web frameworks.",
    "The acronym API stands for Application Programming Interface.",
    "HTTP status code 404 indicates 'Not Found'.",
    "REST stands for Representational State Transfer.",
    "GraphQL is a query language for your API.",
    "NoSQL databases, like MongoDB, are commonly used in modern web development.",
    "The Model-View-Controller (MVC) is a common architectural pattern for web applications.",
    "OAuth is a popular authentication and authorization protocol for APIs.",
    "JSON is a common data format used for web APIs.",
    "WebSocket is a protocol that enables real-time communication in web applications.",
    "Apache is one of the most widely used web servers in the world.",
    "Containers, like Docker, are used for packaging and deploying applications.",
    "The microservices architectural style decomposes applications into small, independent services.",
    "JWT (JSON Web Tokens) are often used for authentication in web applications.",
    "Serverless computing allows you to run code without provisioning or managing servers.",
    "CRUD stands for Create, Read, Update, and Delete - common operations in web applications.",
    "WebSocket is a protocol that enables real-time communication in web applications.",
    "GraphQL is known for reducing over-fetching and under-fetching of data.",
    "Docker containers are lightweight and can be easily moved between environments.",
    "HTTP/2 is a major revision of the HTTP network protocol.",
    "DevOps is a set of practices that combine development and IT operations.",
    "Serverless computing is also known as Function as a Service (FaaS).",
    "WebSockets are used for real-time chat applications and online gaming.",
    "MongoDB is a popular NoSQL database known for its flexibility.",
    "PostgreSQL is a powerful open-source relational database system.",
    "Nginx is a high-performance web server and reverse proxy server.",
    "Server-side rendering (SSR) can improve the initial load time of web pages.",
    "NoSQL databases are often used for handling unstructured or semi-structured data.",
    "WebSockets are commonly used in online collaborative tools and live sports updates.",
    "Amazon Web Services (AWS) is a leading cloud computing platform.",
    "Kubernetes is a popular container orchestration platform.",
    "API rate limiting helps prevent abuse and overuse of your API resources.",
    "HTTP status code 200 means 'OK'.",
    "GraphQL can significantly reduce the number of API requests needed.",
    "AWS Lambda allows you to run code without managing servers.",
    "HTTP/3 is the next major version of the HTTP protocol.",
    "A proxy server can act as an intermediary between clients and backend services.",
    "CORS (Cross-Origin Resource Sharing) controls which domains can access your backend.",
    "OAuth 2.0 is widely used for authentication and authorization in web applications.",
    "A Web Application Firewall (WAF) protects against web application attacks.",
    "WebSocket connections are full-duplex, allowing data to flow in both directions simultaneously.",
    "Microservices often communicate via lightweight protocols like HTTP or message queues.",
    "A/B testing involves comparing two versions of a web application to determine which performs better.",
    "Amazon RDS provides managed relational database services on AWS.",
    "Serverless functions can scale automatically based on demand.",
    "SQL injection is a common security vulnerability in web applications.",
    "API documentation is essential for developers to understand how to use your API.",
    "A load balancer distributes incoming traffic across multiple backend servers.",
    "Immutable infrastructure promotes replacing servers instead of updating them.",
    "API versioning allows you to make changes to your API without breaking existing clients.",
    "WebSocket connections can be secured with the WSS (WebSocket Secure) protocol.",
    "GraphQL supports real-time subscriptions, allowing clients to receive updates.",
    "Content delivery networks (CDNs) improve the performance of web applications by caching content closer to users.",
    "Redis is an in-memory data store often used for caching and real-time analytics.",
    "Kafka is a distributed streaming platform used for building real-time data pipelines.",
    "Inversion of Control (IoC) is a software design principle that promotes loose coupling between components.",
    "Elasticsearch is a search and analytics engine often used for log and event data.",
    "Database indexing can significantly improve query performance.",
    "Continuous Integration (CI) and Continuous Deployment (CD) automate the software delivery process.",
    "API throttling limits the number of requests a client can make to an API within a specified timeframe.",
    "JWTs can be used to carry claims about a user, such as their identity or role.",
    "WebSockets are commonly used in online gaming for real-time interaction.",
    "Distributed systems often use consensus algorithms like Raft or Paxos for coordination.",
    "WebSockets can be used for building interactive chat applications.",
    "Caching can significantly reduce the load on a backend server.",
    "JSON Web Tokens (JWTs) are self-contained and can carry user information.",
    "WebSockets are widely used in online collaboration tools, such as virtual whiteboards.",
    "AWS offers a variety of services for building and hosting web applications.",
    "The 12-factor app methodology outlines best practices for building scalable web applications.",
    "WebSockets can be used for building online multiplayer games.",
    "Amazon S3 is a popular cloud storage service for hosting static assets.",
    "Event sourcing is a pattern for tracking changes to application state.",
    "Kubernetes can automate the deployment, scaling, and management of containerized applications.",
    "HTTP status code 503 indicates 'Service Unavailable'.",
    "Version control systems like Git help manage and track changes to code.",
    "Nginx can serve as a reverse proxy, load balancer, and web server.",
    "WebSockets can be used for building real-time collaborative coding environments.",
    "GraphQL allows clients to request only the data they need, reducing over-fetching.",
    "Serverless functions can be triggered by events, such as HTTP requests or database changes.",
    "Golang (Go) is a programming language known for its efficiency and performance.",
    "Cassandra is a NoSQL database designed for high availability and scalability.",
    "A/B testing can help optimize user experiences and increase conversion rates.",
    "Chaos engineering involves testing how a system behaves under extreme conditions.",
    "Serverless platforms like AWS Lambda are event-driven and stateless.",
    "HTTP status code 401 means 'Unauthorized'.",
    "WebSocket connections are often used for building real-time dashboards.",
    "Kubernetes Operators automate the management of complex applications.",
    "API gateways are used to manage and secure API traffic.",
    "Serverless applications are often billed based on the number of executions and execution time.",
    "CORS headers are used to specify which origins can access resources on a web server.",
    "HTTP status code 500 indicates a generic server error.",
    "Backend developers often work with databases, APIs, and server infrastructure to create the logic and functionality of web applications."
];

export default backendFunFacts;